import type { CatalogSceneId, OllieSceneId } from "@/lib/canvas/stageAssets";
import { isUserSceneLayerId } from "@/lib/canvas/userSceneIds";

/** Backdrop library filters — each scene id maps to one or more categories. */
export const SCENE_CATEGORY_IDS = [
  "solids",
  "urban",
  "nature",
  "water",
  "space",
  "indoor",
  "sports",
  "stage_events",
  "my_scenes",
] as const;
export type SceneCategoryId = (typeof SCENE_CATEGORY_IDS)[number];

export const SCENE_CATEGORY_LABELS: Record<SceneCategoryId, string> = {
  solids: "Solids & grids",
  urban: "City & streets",
  nature: "Nature & outdoors",
  water: "Water & beach",
  space: "Space & night sky",
  indoor: "Indoor & rooms",
  sports: "Sports & play",
  stage_events: "Stage & events",
  my_scenes: "My Scenes",
};

export const SCENE_CATEGORIES_BY_ID = {
  "white_dots": ["solids"] as const,
  "color_light_blue": ["solids"] as const,
  "color_lime_green": ["solids"] as const,
  "color_blue": ["solids"] as const,
  "color_gray": ["solids"] as const,
  "color_black": ["solids"] as const,
  "color_lavender": ["solids"] as const,
  "color_light_gray": ["solids"] as const,
  "color_yellow": ["solids"] as const,
  "color_cyan": ["solids"] as const,
  "color_red": ["solids"] as const,
  "color_green": ["solids"] as const,
  "color_violet": ["solids"] as const,
  "color_orange": ["solids"] as const,
  "sky": ["solids"] as const,
  "mint": ["solids"] as const,
  "park": ["nature"] as const,
  "path": ["nature"] as const,
  "pathway": ["nature"] as const,
  "cityroad": ["urban"] as const,
  "bg01": ["urban"] as const,
  "bg02": ["nature", "urban"] as const,
  "bg03": ["urban"] as const,
  "bg04": ["urban"] as const,
  "bg05": ["nature"] as const,
  "bg06": ["nature"] as const,
  "bg07": ["nature"] as const,
  "bg08": ["nature"] as const,
  "bg09": ["nature"] as const,
  "bg10": ["nature"] as const,
  "bg11": ["water"] as const,
  "bg12": ["water"] as const,
  "bg13": ["water"] as const,
  "bg14": ["water"] as const,
  "bg15": ["water"] as const,
  "bg16": ["water"] as const,
  "bg17": ["water"] as const,
  "bg18": ["indoor"] as const,
  "bg19": ["indoor"] as const,
  "bg20": ["stage_events"] as const,
  "bg21": ["indoor"] as const,
  "bg22": ["stage_events"] as const,
  "bg23": ["stage_events"] as const,
  "bg24": ["stage_events"] as const,
  "bg25": ["stage_events"] as const,
  "bg26": ["stage_events"] as const,
  "bg27": ["stage_events"] as const,
  "bg28": ["indoor"] as const,
  "bg29": ["indoor"] as const,
  "bg30": ["indoor"] as const,
  "bg31": ["indoor"] as const,
  "bg32": ["indoor"] as const,
  "bg33": ["sports"] as const,
  "bg34": ["sports"] as const,
  "bg35": ["sports"] as const,
  "bg36": ["sports", "urban"] as const,
  "bg37": ["space"] as const,
  "bg38": ["space"] as const,
  "bg39": ["space"] as const,
  "bg40": ["space"] as const,
  "bg41": ["water"] as const,
  "bg42": ["nature"] as const,
  "bg43": ["nature"] as const,
  "bg44": ["nature"] as const,
  "bg45": ["nature", "water"] as const,
  "bg46": ["nature", "water"] as const,
  "bg47": ["nature"] as const,
  "bg48": ["nature"] as const,
  "bg49": ["nature"] as const,
  "bg50": ["stage_events"] as const,
  "bg51": ["nature", "urban"] as const,
  "bg52": ["urban"] as const,
  "bg53": ["nature"] as const,
  "bg54": ["urban"] as const,
  "bg55": ["nature"] as const,
  "bg56": ["urban"] as const,
  "bg57": ["sports"] as const,
  "bg58": ["sports"] as const,
  "bg59": ["urban"] as const,
  "bg60": ["nature"] as const,
  "bg61": ["indoor"] as const,
  "bg62": ["indoor"] as const,
  "bg63": ["indoor"] as const,
  "bg64": ["indoor"] as const,
  "bg65": ["indoor"] as const,
  "bg66": ["indoor"] as const,
  "bg67": ["water"] as const,
  "bg68": ["water"] as const,
  "bg69": ["indoor"] as const,
  "bg70": ["water"] as const,
  "bg71": ["indoor"] as const,
  "bg72": ["nature"] as const,
  "bg73": ["indoor"] as const,
  "bg74": ["indoor"] as const,
  "bg75": ["space"] as const,
  "bg76": ["space"] as const,
  "bg77": ["nature"] as const,
  "bg78": ["nature"] as const,
  "bg79": ["nature"] as const,
  "bg80": ["nature"] as const,
  "bg81": ["nature"] as const,
  "bg82": ["urban"] as const,
  "bg83": ["water"] as const,
  "bg84": ["water"] as const,
  "bg85": ["urban"] as const,
  "bg86": ["urban"] as const,
  "bg87": ["nature"] as const,
  "winterforest": ["nature", "stage_events"] as const,
  "christmasmarket": ["urban", "stage_events"] as const,
  "aurorawinterpath": ["nature", "space"] as const,
  "folkstarfloral": ["stage_events"] as const,
  "faithsymbolpattern": ["stage_events"] as const,
  "templemeditation": ["indoor", "stage_events"] as const,
  "mosquefacade": ["urban"] as const,
} as const satisfies Record<CatalogSceneId, readonly SceneCategoryId[]>;

export function sceneMatchesCategory(
  sceneId: OllieSceneId,
  filter: SceneCategoryId | "all",
): boolean {
  if (filter === "all") return true;
  if (filter === "my_scenes") return isUserSceneLayerId(sceneId);
  if (isUserSceneLayerId(sceneId)) return false;
  const cats =
    SCENE_CATEGORIES_BY_ID[sceneId as keyof typeof SCENE_CATEGORIES_BY_ID];
  if (!cats) return false;
  return (cats as readonly SceneCategoryId[]).includes(filter);
}
